#!/bin/sh
#
# redis        init file for starting up the redis daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the redis daemon.

# Source function library.
. /etc/rc.d/init.d/functions

name="redis-sentinel"
exec="/usr/local/bin/$name"
appname=`basename $0 | sed 's/.*sentinel/sentinel/g'`
pidfile="/var/run/sentinel/${appname}.pid"
sentinel_config="/etc/sentinel/${appname}.conf"
lockfile=/var/lock/subsys/${appname}

[ -e /etc/sysconfig/sentinel ] && . /etc/sysconfig/sentinel

[ ! -f /etc/sysconfig/sentinel ] && mkdir -p /var/lib/sentinel/${appname} && chown redis.redis /var/lib/sentinel/${appname}

[ ! -d /var/run/sentinel ] && mkdir -p /var/run/sentinel && chown redis.redis /var/run/sentinel

[ -f $sentinel_config ] && chown redis.redis $sentinel_config

start() {
    [ -f $sentinel_config ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon --user ${REDIS_USER-redis} "$exec $sentinel_config"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killproc -p $pidfile $name
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
